
REFERENCE_DATA: /proj/ngi2024001/nobackup/bin/wp3_tc/design_and_ref_files

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp3_tc/marple_rd_tc_{{PIPELINE_VERSION}}/hydra-genetics

resources: config/resources.miarka.yaml

reference:
  annovar: '{{REFERENCE_DATA}}/marple/annovar/'
  fasta: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta'
  fai: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta.fai'
  sites: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.known_indels.vcf.gz' #Needed?
  design_bed: '{{REFERENCE_DATA}}/marple/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.bed'
  design_intervals: '{{REFERENCE_DATA}}/marple/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.intervals'
  exon_bed: '{{REFERENCE_DATA}}/marple/Twist_Cancer_230602_hg38_coding_exons.bed'
  exon_intervals: '{{REFERENCE_DATA}}/marple/Twist_Cancer_230602_hg38_coding_exons.intervals'
  pgrs_bed: '{{REFERENCE_DATA}}/marple/Twist_Cancer_230707_hg38_pgrs_snps.bed'

bwa_mem:
  amb: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta.amb'
  ann: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta.ann'
  bwt: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta.bwt'
  pac: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta.pac'
  sa: '{{REFERENCE_DATA}}/marple/reference_grasnatter/homo_sapiens.fasta.sa'

exomedepth_call:
  bedfile: '{{REFERENCE_DATA}}/marple/Twist_Cancer_230706_hg38_TE-98982205-wPGRS.merged_200bpwindows.bed'
  exonsfile: '{{REFERENCE_DATA}}/marple/exons_GRCh38_ensembl109.txt'
  genesfile: '{{REFERENCE_DATA}}/marple/genes_GRCh38_ensembl109.txt'

export_qc_xlsx_report:
  wanted_transcripts: '{{REFERENCE_DATA}}/marple/wanted_transcripts.txt'

melt:
  bed: '{{REFERENCE_DATA}}/marple/melt/Hg38.genes.bed'
  mei: '{{REFERENCE_DATA}}/marple/melt/mei_list.txt'

mosaicforecast_genotype_prediction:
  model_trainedSNP: '{{REFERENCE_DATA}}/marple/150xRFmodel_addRMSK_Refine.rds' # 200xRFmodel_addRMSK_Refine.rds or deletions_250x.RF.rds(phase) or insertions_250x.RF.rds(phase)
  model_trainedINS: '{{REFERENCE_DATA}}/marple/insertions_250x.RF.rds' # 200xRFmodel_addRMSK_Refine.rds or deletions_250x.RF.rds(phase) or insertions_250x.RF.rds(phase)
  model_trainedDEL: '{{REFERENCE_DATA}}/marple/deletions_250x.RF.rds' # 200xRFmodel_addRMSK_Refine.rds or deletions_250x.RF.rds(phase) or insertions_250x.RF.rds(phase)

vep:
  vep_cache: '{{REFERENCE_DATA}}/marple/VEP/'

